### ISSUE TITLE
Error code documentation

### ISSUE THREAD

**Issue by dstoup** [gjefferyes/RomVault#20]
It would be helpful to have documentation about the various errors I might see, what they mean and how I might correct the situation.

This feature request is prompted by my first use of RomVault, while following the youtube tutorial. When I put ROMs in ToSort and click ScanROMs, I get the following error for many files, "ZipCentralDirError", but have know way of knowing what that means.

**Comment by gjefferyes** [comment]
ZipGood,
ZipFileLocked,   = is trying to delete the file but it is locked by the file system
ZipFileCountError,   = the zip file is corrupt, and the number of files in the zip does not match the central directory count of the number of files it is expecting
ZipSignatureError    = the zip file is corrupt, an unrecognized data block signature was found in the zip
ZipExtraDataOnEndOfZip,   = there are bytes past what should be the end of the zip file
ZipUnsupportedCompression    = RomVault only support uncompressed and zlib style deflate, any other compression types in the zip will give this error, you should use another zip tool to (de)recompress this zip file.
ZipLocalFileHeaderError,    =  the zip file is corrupt, the central directory of files is not correctly point at the zip data.
ZipCenteralDirError,    = the zip file is corrupt, the central directory info does not match the file info
ZipEndOfCentralDirectoryError,   = the zip file is corrupt, the central directory is shorter than it should be.
ZipCRCDecodeError    =  the zip file is corrupt, the uncompressed data does not match the expected CRC
ZipDecodeError,  =  the zip file is corrupt, the compressed data stream is corrupt and cannot be uncompressed.


and time you get an the zip file is corrupt error, you could try repairing the zip file with a tool like winrar, otherwise you are out of luck.

**Comment by LnmVolbo** [comment]
Thanks for the "Rosetta Stone" of zip file errors!
